name: Tests

on: push

jobs:
    tests:
        runs-on: windows-latest

        strategy:
            matrix:
                r-version: ["3.6", 4.2"]
        
        steps:
            - uses: actions/checkout@v2
            - uses: r-lib/actions/setup-r-dependencies@v2
              with:
                extra-packages: |
                  any::testthat
            - name: run unit tests
              run: Rscript test/unitTests.R